name: Build OpenJDK17 for Android

on:
  workflow_dispatch:
  schedule:
  - cron: "20 5 2,9,16,23 * *"

jobs:
  build_android:
    strategy:
      matrix:
        arch: [ "aarch32", "aarch64", "x86", "x86_64" ]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.4
    - name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 17
        distribution: temurin
    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt -y install systemtap-sdt-dev libxtst-dev libasound2-dev libelf-dev libfontconfig1-dev libx11-dev libxext-dev libxrandr-dev libxrender-dev libxtst-dev libxt-dev
        git clone --depth 1 --branch buildjre17 https://github.com/Vera-Firefly/android-openjdk-build
    - name: Build with CI build script
      run: |
        cd android-openjdk-build
        bash "ci_build_arch_${{matrix.arch}}.sh"
    - name: Upload JDK build output
      uses: actions/upload-artifact@v4.3.3
      with:
        name: "jdk17-${{matrix.arch}}"
        path: android-openjdk-build/jdk17*.tar.xz
    - name: Upload JRE build output
      uses: actions/upload-artifact@v4.3.3
      with:
        name: 'jre17-${{matrix.arch}}'
        path: android-openjdk-build/jre17*.tar.xz
    - name: Upload JRE debuginfo build output
      uses: actions/upload-artifact@v4.3.3
      with:
        name: "jre17-debuginfo-${{matrix.arch}}"
        path: android-openjdk-build/dizout
    - name: Upload jspawnhelper lib output
      if: ${{ matrix.arch == 'aarch64'}}
      uses: actions/upload-artifact@v4.3.3
      with:
        name: jsph-17
        path: android-openjdk-build/libjsph17.so

  pojav:
    needs: build_android
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.4
    - name: Get jre17-aarch32
      uses: actions/download-artifact@v4.1.7
      with:
        name: jre17-aarch32
        path: pojav
    - name: Get jre17-aarch64
      uses: actions/download-artifact@v4.1.7
      with:
        name: jre17-aarch64
        path: pojav
    - name: Get jre17-x86
      uses: actions/download-artifact@v4.1.7
      with:
        name: jre17-x86
        path: pojav
    - name: Get jre17-x86_64
      uses: actions/download-artifact@v4.1.7
      with:
        name: jre17-x86_64
        path: pojav
    - name: Repack JRE
      run: |
        git clone --depth 1 --branch buildjre17 https://github.com/Vera-Firefly/android-openjdk-build
        bash "android-openjdk-build/repackjre.sh" $GITHUB_WORKSPACE/pojav $GITHUB_WORKSPACE/pojav/jre17-pojav
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
          name: jre17-pojav
          path: pojav/jre17-pojav/*
